apiVersion: v1
kind: Service
metadata:
  name: red-service-active
  namespace: skills
spec:
  type: NodePort
  selector:
    app: red
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: red-service-preview
  namespace: skills
spec:
  type: NodePort
  selector:
    app: red
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
